import { Advent_Pro } from "next/font/google";
import "./globals.css";

const advent_pro = Advent_Pro({

  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={advent_pro.className}>
      <body

      >
      ПРИВЕТ
        {children}
      </body>
    </html>
  );
}
